# -*- coding: utf-8 -*-
"""sql_tune_gguf_main.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1str8qS2ssTlokgMnvr5LOus1nEPDdY1P

Install required modules
"""

!pip install --upgrade pip
!pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu121
!pip install transformers datasets peft trl bitsandbytes accelerate

"""Check whether the required modules installed or not"""

import torch
import transformers
import datasets
import peft
import trl
import bitsandbytes

print("Torch:", torch.__version__)
print("Transformers:", transformers.__version__)
print("PEFT:", peft.__version__)
print("TRL:", trl.__version__)
print("BitsAndBytes:", bitsandbytes.__version__)

"""Upload the sql json file for inputs"""

from google.colab import files
uploaded = files.upload()

"""Load model and Tokenizer - the purpose is Load base LLM
Tokenizer converts: text → tokens → model input

"""

import os
import torch
from transformers import AutoTokenizer, AutoModelForCausalLM, BitsAndBytesConfig
from datasets import load_dataset
from peft import LoraConfig
from trl import SFTTrainer, SFTConfig

model_name = "TinyLlama/TinyLlama-1.1B-Chat-v1.0"

tokenizer = AutoTokenizer.from_pretrained(model_name)

quantization_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_quant_type="nf4",
    bnb_4bit_compute_dtype=torch.float16,
    bnb_4bit_use_double_quant=False,
)

model = AutoModelForCausalLM.from_pretrained(
    model_name,
    quantization_config=quantization_config,
    device_map="auto"
)

peft_config = LoraConfig(
    r=16,
    lora_alpha=32,
    lora_dropout=0.05,
    bias="none",
    task_type="CAUSAL_LM"
)

dataset = load_dataset(
    "json",
    data_files="/content/sql_d.json"
)



training_args = SFTConfig(
    output_dir="./results",
    per_device_train_batch_size=2,
    num_train_epochs=3,
    learning_rate=2e-4,
    logging_steps=10,
    save_steps=100,
    fp16=False,
    bf16=False
)




trainer = SFTTrainer(
    model=model,
    train_dataset=dataset["train"],
    peft_config=peft_config,
    args=training_args
)

trainer.train()
trainer.model.save_pretrained("sql_model")
tokenizer.save_pretrained("sql_model")

"""Testing by giving a query"""

from transformers import AutoTokenizer, AutoModelForCausalLM

model_path = "/content/sql_model"

tokenizer = AutoTokenizer.from_pretrained(model_path)
model = AutoModelForCausalLM.from_pretrained(model_path)

prompt = "List all employees"

inputs = tokenizer(prompt, return_tensors="pt")
outputs = model.generate(**inputs, max_new_tokens=100)

print(tokenizer.decode(outputs[0], skip_special_tokens=True))

"""Quantization - Reduce memory usage -Make model run in Colab GPU
Without this:
-model won’t fit in memory

"""

from transformers import AutoTokenizer, AutoModelForCausalLM
from peft import PeftModel
import torch

# base model
base_model = "TinyLlama/TinyLlama-1.1B-Chat-v1.0"

# trained adapter
adapter_path = "/content/sql_model"

# load tokenizer
tokenizer = AutoTokenizer.from_pretrained(adapter_path)

# load base model
model = AutoModelForCausalLM.from_pretrained(
    base_model,
    device_map="auto",
    dtype=torch.float16
)

model = PeftModel.from_pretrained(model, adapter_path)

question = "feeders in delhi with capacity less than 80"

prompt = f"Question: {question} SQL:"

inputs = tokenizer(prompt, return_tensors="pt").to(model.device)

output = model.generate(
    **inputs,
    max_new_tokens=100,
    temperature=0
)

result = tokenizer.decode(output[0], skip_special_tokens=True)

print(result)

"""If we want only fine tuned model we have to make it zip to download- should execute the next 2 cells"""

!zip -r sql_model.zip /content/sql_model

from google.colab import files
files.download("sql_model.zip")

"""Merging the base model and Adapter model which was acquired after fine tuning"""

import torch, torchvision

print(torch.__version__)
print(torchvision.__version__)

import torch
from transformers import AutoModelForCausalLM, AutoTokenizer
from peft import PeftModel

base_model = "TinyLlama/TinyLlama-1.1B-Chat-v1.0"
adapter_path = "/content/sql_model"   # your trained LoRA path

# Load base model
model = AutoModelForCausalLM.from_pretrained(base_model, torch_dtype=torch.float16)

# Load LoRA adapter
model = PeftModel.from_pretrained(model, adapter_path)

# 🔥 Merge LoRA
model = model.merge_and_unload()

# Save merged model
model.save_pretrained("/content/merged_sql_model")

# Save tokenizer (VERY IMPORTANT)
tokenizer = AutoTokenizer.from_pretrained(base_model)
tokenizer.save_pretrained("/content/merged_sql_model")

print("✅ Merge completed")

"""clone llama.cpp : Tool to convert model → GGUF

"""

# Commented out IPython magic to ensure Python compatibility.
# Commented out IPython magic to ensure Python compatibility.
#!git clone https://github.com/ggerganov/llama.cpp
# %cd llama.cpp
#!pip install -r requirements.txt

!rm -rf /content/llama.cpp
!git clone https://github.com/ggerganov/llama.cpp
# %cd llama.cpp
!pip install -r requirements.txt

"""check did we get all the required files or not"""

!ls /content/merged_sql_model

"""If we could not find all the required files in the merged_sql_model- execute below code to fix the tokenizer issue"""

from transformers import AutoTokenizer

base_model = "TinyLlama/TinyLlama-1.1B-Chat-v1.0"

tokenizer = AutoTokenizer.from_pretrained(base_model, use_fast=False)

tokenizer.save_pretrained("/content/merged_sql_model")

print("✅ Tokenizer fixed")

"""Recheck again"""

!ls /content/merged_sql_model

"""Install gguf file to the content"""

!python /content/llama.cpp/convert_hf_to_gguf.py /content/merged_sql_model --outfile /content/sql_model.gguf

"""Download gguf file"""

from google.colab import files
files.download("/content/sql_model.gguf")

"""If the downloading is not possible due large size - we can mount the file to drive and from there we can download it"""

from google.colab import drive
drive.mount('/content/drive')

"""Check whether the file mounted to drive or not"""

!ls /content

!cp /content/sql_model.gguf /content/drive/MyDrive/sql_model.gguf

!ls /content/drive/MyDrive